### PR TITLE
SET owner reference for tekton pipelines and tasks

### LINKED ISSUE #40: Resources created by the operator do not get cleaned up when CR is deleted
## Bug Description

The operator creates various resources (pipelines, subscriptions) but not all of them are owned by the custom resource and end up not getting removed when the OperatorPipeline CR is deleted

## Steps to Reproduce:

1) Created OperatorPipeline CR `oc apply -f config/samples/certification_v1alpha1_operatorpipeline.yaml`
2) Wait for operator to resolve
3) Delete OperatorPipeline CR `oc delete -f config/samples/certification_v1alpha1_operatorpipeline.yaml`
4) View pipelines (or any other created resources) in the UI and see that they still exist

## Expected Result

All resources directly created by the operator get removed 

## Actual Result

Some resources (pipelines specifically) stick around

## Additional Context

Mostly has to do with ownership of the new resources not being set to the OperatorPipeline resource. This will likely not be a standard case because we run yaml from another repo to create most (if not all) of the resources in question.
https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/main/controllers/dependencies.go#L24-L76

### PR DESCRIPTION
**Pull request by acmenezes**
This commit includes the following changes:

- Adds a pointer field on the main reconciler struct to the operator pipeline CR
- Update OperatorPipeline field on main reconciler before reconciling resources
- Uses OperatorPipeline on dependencies.go to create the owner reference and set
it for pipelines and tasks.

Those changes enable background deletion when the CR is deleted by the user.

closes #40 

Observations:

It's still not clear if the subscription should be deleted with the CR deletion since it installs the tekton operator once but may have multiple CRs depending on it. I'm not sure on that point. Glad to hear other thoughts on this.

Also although secrets are used by the CR they are not created or managed by the CR. Which means that it's not owned by the CR. I guess they shouldn't be deleted when deleting the CR. Also would like to hear the team's thoughts on this.

### CODE REVIEW

File: controllers/dependencies.go [hunk 1]
```diff
@@ -97,6 +97,18 @@ func (r *OperatorPipelineReconciler) applyManifests(fileName string, Namespace s
...
+	// Setting owner reference on created resources to
+	// allow for background deletion
+	ownerRefs := []metav1.OwnerReference{{
+		APIVersion: r.OperatorPipeline.APIVersion,
+		Kind:       r.OperatorPipeline.Kind,
+		Name:       r.OperatorPipeline.Name,
+		UID:        r.OperatorPipeline.UID,
+	}}
+
+	obj.SetOwnerReferences(ownerRefs)
```
Comment (samira-barouti) [inline controllers/dependencies.go:110]: I believe this method should be leveraged to set the controller as the owner:
https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#SetControllerReference

**Review by samira-barouti — CHANGES_REQUESTED** [review]

File: controllers/dependencies.go (hunk 1 above)
Comment (acmenezes) [reply controllers/dependencies.go:110]: Interesting. I'm not sure about that. We can both use the controllerutil or the api machinery one that you see on the code. The struct for ownerRefs has other two optional fields being one a boolean that allows for setting the controller as owner. My question is: wouldn't the controller own the primary resource? Being the secondary ones owned by the primary? Like in the code? It actually works pretty well when the CR is deleted. But I didn't test the other one. I'll check that out. And come back here.

Comment (samira-barouti) [reply controllers/dependencies.go:110]: yep, SetOwnerReference set the `BlockOwnerDeletion` to false, but SetControllerReference set it true. Here is the description of the field: https://github.com/kubernetes/apimachinery/blob/19377c9f105d03037e842e151d4605fef730b073/pkg/apis/meta/v1/types.go#L329

File: controllers/operatorpipeline_controller.go [hunk 2]
```diff
@@ -64,6 +65,10 @@ func (r *OperatorPipelineReconciler) Reconcile(ctx context.Context, req ctrl.Req
 		return ctrl.Result{}, err
 	}
 
+	// setting pipeline pointer on reconciler struct to allow usage
+	// on subreconciler functions
+	r.OperatorPipeline = pipeline
```
Comment (bcrochet) [inline controllers/operatorpipeline_controller.go:70]: This seems like a bad idea from a concurrency perspective. I'd have to do some investigation, but first glance seems like a problem.
Scenario: Two reconciles happen back to back. Before the first reconcile is complete, the second occurs and overwrites this field. The first reconcile is now in an inconsistent state, as it was operating on a different CR for half of it's reconcile. 

IIUC, there is only one Reconciler. Now, if you wanted to use a mutex, that would be fine.

File: controllers/dependencies.go (hunk 1 above)
Comment (bcrochet) [reply controllers/dependencies.go:110]: Also, the controllerutil.SetOwnerReference does this for you. You don't have to handle setting all of the metav1.OwnerReference fields.

Comment (acornett21) [reply controllers/dependencies.go:110]: @samira-barouti Is correct we need to use the method linked. We _also_ need to refactor from top town for this controller to this dependecy file to pass in the `OperatorPipeline` struct and not the `meta` struct. SetControllerReference throws an exception when `meta` is passed in. I was testing this extensively yesterday and it does not work otherwise.

**Comment by acornett21** [comment]
We also need to add an `owns` in the below code for `task` and `pipeline` resources.
https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/193baab1c5c3723ca1537025945953a6184f40b6/controllers/operatorpipeline_controller.go#L79

**Comment by acornett21** [comment]
> > We also need to add an `owns` in the below code for `task` and `pipeline` resources.
> > https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/193baab1c5c3723ca1537025945953a6184f40b6/controllers/operatorpipeline_controller.go#L79
> 
> Hi @acornett21 , actually the owns function that belongs to the builder package on controller runtime is setting the watches and enqueueRequestForOwner on behalf of secondary resources. Same thing applies to the setControllerReferece mentioned by @samira-barouti. Either one or the other should be used. I don't think there is a case to use both of them. The operator-sdk way of doing that is using the setupWithManager function calling newControllerManagedBy to accomplish that. It is, behind the scenes, building a complex controller object that is passed as a runnable to the manager workload and started by the manager. That doesn't solve the owner reference element of it though and therefore may not be exactly the same thing this PR addresses. I'm working on this and will answer each one of those comments today as well as update this PR with a rebased push. Thanks!

In my testing, I needed to do _both_ `owns` and `SetControllerReference`, just doing `owns` yield no affected on the `task/pipeline` resources.

File: controllers/dependencies.go (hunk 1 above)
Comment (acmenezes) [reply controllers/dependencies.go:110]: So in conclusion: 
1 - SetOwnerReference solves the problem of this PR but...
2 - SetControllerReference solves 2 problems:
  a. the background deletion
  b. mark the secondary resource to signal events
3 - The Owns function needs to work in conjunction with SetControllerReference. That is basically the controller saying you generate events and I'm listening. So if you delete a single pipeline or tasks it also triggers the controller and it reapplies all the resources again. How useful is this in this case is a different discussion.

That said all changes are implemented now.

File: controllers/operatorpipeline_controller.go (hunk 2 above)
Comment (acmenezes) [reply controllers/operatorpipeline_controller.go:70]: As we discussed today, there is way more behind the scenes than a simple struct loading the data. Workers are quite independent of each other. But since it's a little bit obscure I also agree to go through the most comfortable path here. BTW thanks for the help with the code and all tips on rebasing this.

**Comment by acmenezes** [comment]
> > > We also need to add an `owns` in the below code for `task` and `pipeline` resources.
> > > https://github.com/redhat-openshift-ecosystem/operator-certification-operator/blob/193baab1c5c3723ca1537025945953a6184f40b6/controllers/operatorpipeline_controller.go#L79
> > 
> > 
> > Hi @acornett21 , actually the owns function that belongs to the builder package on controller runtime is setting the watches and enqueueRequestForOwner on behalf of secondary resources. Same thing applies to the setControllerReferece mentioned by @samira-barouti. Either one or the other should be used. I don't think there is a case to use both of them. The operator-sdk way of doing that is using the setupWithManager function calling newControllerManagedBy to accomplish that. It is, behind the scenes, building a complex controller object that is passed as a runnable to the manager workload and started by the manager. That doesn't solve the owner reference element of it though and therefore may not be exactly the same thing this PR addresses. I'm working on this and will answer each one of those comments today as well as update this PR with a rebased push. Thanks!
> 
> In my testing, I needed to do _both_ `owns` and `SetControllerReference`, just doing `owns` yield no affected on the `task/pipeline` resources. Also, if someone uninstalls the operator, we want those resources cleaned up IMO.

Check the replay on the first comment. Totally agree.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by samira-barouti — APPROVED** [review]
/lgtm
